=== 707eric/cti-stix2-json-schemas/schemas/common/bundle.json
{
  "$id": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/common/bundle.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "bundle",
  "description": "A Bundle is a collection of arbitrary STIX Objects and Marking Definitions grouped together in a single container.",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "description": "The type of this object, which MUST be the literal `bundle`.",
      "enum": [
        "bundle"
      ]
    },
    "id": {
      "allOf": [
        {
          "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/common/identifier.json",
          "description": "An identifier for this bundle. The id field for the Bundle is designed to help tools that may need it for processing, but tools are not required to store or track it. "
        },
        {
          "title": "id",
          "pattern": "^bundle--"
        }
      ]
    },
    "spec_version": {
      "type": "string",
      "enum": [
        "2.0"
      ],
      "description": "The version of the STIX specification used to represent the content in this bundle."
    },
    "objects": {
      "type": "array",
      "description": "Specifies a set of one or more STIX Objects.",
      "items": {
        "anyOf": [
          {
            "oneOf": [
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/attack-pattern.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/campaign.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/course-of-action.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/identity.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/indicator.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/intrusion-set.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/malware.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/common/marking-definition.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/observed-data.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sros/relationship.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/report.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sros/sighting.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/threat-actor.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/tool.json"
              },
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/sdos/vulnerability.json"
              }
            ]
          },
          {
            "allOf": [
              {
                "$ref": "http://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/schemas/common/core.json"
              },
              {
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "The type of this object, which for custom objects cannot be one of those defined in the specification.",
                    "not": {
                      "enum": [
                        "attack-pattern",
                        "campaign",
                        "course-of-action",
                        "identity",
                        "indicator",
                        "intrusion-set",
                        "malware",
                        "marking-definition",
                        "observed-data",
                        "relationship",
                        "report",
                        "sighting",
                        "threat-actor",
                        "tool",
                        "vulnerability"
                      ]
                    }
                  }
                }
              }
            ]
          }
        ]
      },
      "minItems": 1
    }
  },
  "required": [
    "type",
    "id",
    "spec_version"
  ]
}

=== 707eric/cti-stix2-json-schemas/examples/idioms/kill-chain.json
{
  "type": "bundle",
  "id": "bundle--91d9b5a2-b63b-431b-ab56-aba30ab36809",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "indicator",
      "id": "indicator--f33c2b75-aa60-4ffb-9829-3746ef233311",
      "version": 1,
      "created": "2014-10-21T21:10:09.423000Z",
      "modified": "2014-10-21T21:10:09.423000Z",
      "valid_from": "2014-10-21T21:10:09.423000Z",
      "pattern": "ipv4addr:value = '58.246.0.0/15'",
      "labels": [
        "malicious-activity"
      ],
      "kill_chain_phases": [
        {
          "kill_chain_name": "lockheed-martin-cyber-kill-chain",
          "phase_name": "command-and-control"
        }
      ]
    }
  ]
}

=== 707eric/cti-stix2-json-schemas/examples/idioms/victim-targeting-for-a-campaign.json
{
  "type": "bundle",
  "id": "bundle--bf35a4b5-e102-463d-9105-4d7a6e2d78bc",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "campaign",
      "id": "campaign--c831ab93-ff84-9cda-2bd8-b094004da969",
      "created": "2014-02-20T09:00:00.000000Z",
      "modified": "2014-02-20T09:00:00.000000Z",
      "name": "Operation Alpha"
    },
    {
      "type": "relationship",
      "id": "relationship--81c279d9-c30e-4d12-8412-39192384efe7",
      "created": "2014-02-20T09:00:00.000000Z",
      "modified": "2014-02-20T09:00:00.000000Z",
      "relationship_type": "targets",
      "source_ref": "campaign--c831ab93-ff84-9cda-2bd8-b094004da969",
      "target_ref": "identity--4fde045a-b25f-f035-e8d0-29c9d5130cd9"
    },
    {
      "type": "identity",
      "id": "identity--4fde045a-b25f-f035-e8d0-29c9d5130cd9",      
      "created": "2014-02-20T09:00:00.000000Z",
      "modified": "2014-02-20T09:00:00.000000Z",
      "name": "Financial Service Customers",
      "identity_class": "group",
      "sectors": [
        "financial-services"
      ]
    }
  ]
}

=== 707eric/cti-stix2-json-schemas/examples/using-granular-markings.json
{
  "type": "bundle",
  "id": "bundle--963410f2-fd7d-4d80-937c-8ad3aed5f432",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "identity",
      "id": "identity--b38dfe21-7477-40d1-aa90-5c8671ce51ca",
      "created": "2017-04-27T16:18:24.318Z",
      "modified": "2017-04-27T16:18:24.318Z",
      "name": "Gotham National Bank",
      "identity_class": "organization",
      "contact_information": "contact@gothamnational.com",
      "sectors": [
        "financial-services"
      ]
    },
    {
      "type": "marking-definition",
      "id": "marking-definition--5ca625cc-b52f-4f52-a4c5-c629e44acc08",
      "created": "2017-04-27T16:18:24.318Z",
      "created_by_ref": "identity--b38dfe21-7477-40d1-aa90-5c8671ce51ca",
      "definition_type": "tlp",
      "definition": {
        "tlp": "green"
      }
    },
    {
      "type": "marking-definition",
      "id": "marking-definition--074132b9-ef15-4cf3-b20e-761c26e066f9",
      "created": "2017-04-27T16:18:24.318Z",
      "created_by_ref": "identity--b38dfe21-7477-40d1-aa90-5c8671ce51ca",
      "definition_type": "tlp",
      "definition": {
        "tlp": "amber"
      }
    },
    {
      "type": "marking-definition",
      "id": "marking-definition--ff5a5d1b-7f27-4001-981b-935cc1cf9d20",
      "created": "2017-04-27T16:18:24.318Z",
      "created_by_ref": "identity--b38dfe21-7477-40d1-aa90-5c8671ce51ca",
      "definition_type": "tlp",
      "definition": {
        "tlp": "red"
      }
    },
    {
      "type": "indicator",
      "id": "indicator--1ed8caa7-a708-4706-b651-f1186ede6ca1",
      "created": "2017-04-27T16:18:24.318Z",
      "modified": "2017-04-27T16:18:24.318Z",
      "created_by_ref": "identity--b38dfe21-7477-40d1-aa90-5c8671ce51ca",
      "name": "Phishing email address",
      "description": "Messages from this email address have attempted to get users to click on a site resembling Gotham National Bank's official site but is instead an attempt to steal credentials.",
      "labels": [
        "malicious-activity",
        "phishing"
      ],
      "pattern": "[email-message:from_ref.value MATCHES '.+\\\\banking@g0thamnatl\\\\.com$']",
      "valid_from": "2017-04-27T16:18:24.318Z",
      "granular_markings": [
        {
          "marking_ref": "marking-definition--ff5a5d1b-7f27-4001-981b-935cc1cf9d20",
          "selectors": [
            "pattern",
            "description"
          ]
        },
        {
          "marking_ref": "marking-definition--074132b9-ef15-4cf3-b20e-761c26e066f9",
          "selectors": [
            "name",
            "labels.[1]"
          ]
        },
        {
          "marking_ref": "marking-definition--5ca625cc-b52f-4f52-a4c5-c629e44acc08",
          "selectors": [
            "labels.[0]",
            "valid_from"
          ]
        }
      ]
    }
  ]
}

=== 707eric/cti-stix2-json-schemas/examples/idioms/identifying-a-threat-actor-profile.json
{
  "type": "bundle",
  "id": "bundle--c9567f73-3803-415c-b06e-2b0622830e5d",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "threat-actor",
      "id": "threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428",
      "version": 1,
      "created": "2014-11-19T23:39:03.893348Z",
      "modified": "2014-11-19T23:39:03.893348Z",
      "name": "Disco Team Threat Actor Group",
      "labels": [
        "crime-syndicate"
      ]
    },
    {
      "type": "identity",
      "id": "identity--733c5838-34d9-4fbf-949c-62aba761184c",
      "version": 1,
      "created": "2016-08-23T18:05:49.307000Z",
      "modified": "2016-08-23T18:05:49.307000Z",
      "name": "Disco Team",
      "identity_class": "organization",
      "contact_information": "disco-team@stealthemail.com"
    },
    {
      "type": "relationship",
      "id": "relationship--966c5838-34d9-4fbf-949c-62aba7611837",
      "version": 1,
      "created": "2016-08-23T18:05:49.307000Z",
      "modified": "2016-08-23T18:05:49.307000Z",
      "relationship_type": "attributed-to",
      "source_ref": "threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428",
      "target_ref": "identity--733c5838-34d9-4fbf-949c-62aba761184c"
    }
  ]
}

=== 707eric/cti-stix2-json-schemas/examples/idioms/defining-campaigns-vs-threat-actors.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "campaign",
      "id": "campaign--e5268b6e-4931-42f1-b379-87f48eb41b1e",
      "created": "2014-08-08T15:50:10.983728Z",
      "modified": "2014-08-08T15:50:10.983728Z",
      "name": "Compromise of ATM Machines"
    },
    {
      "type": "relationship",
      "id": "relationship--d07b0cc3-11eb-4906-9e0b-4bcca5f408e4",
      "created": "2014-08-08T15:50:10.983728Z",
      "modified": "2014-08-08T15:50:10.983728Z",
      "relationship_type": "targets",
      "source_ref": "campaign--e5268b6e-4931-42f1-b379-87f48eb41b1e",
      "target_ref": "identity--2d1c6ab3-5e4e-48ac-a32b-f0c01c2836a8"
    },
    {
      "type": "relationship",
      "id": "relationship--5cc8ddc2-4346-4ba1-a997-1b42872b02b0",
      "created": "2014-08-08T15:50:10.983728Z",
      "modified": "2014-08-08T15:50:10.983728Z",
      "relationship_type": "attributed-to",
      "source_ref": "campaign--e5268b6e-4931-42f1-b379-87f48eb41b1e",
      "target_ref": "threat-actor--56f3f0db-b5d5-431c-ae56-c18f02caf500"
    },
    {
      "type": "threat-actor",
      "id": "threat-actor--56f3f0db-b5d5-431c-ae56-c18f02caf500",
      "created": "2014-08-08T15:50:10.983629Z",
      "modified": "2014-08-08T15:50:10.983629Z",
      "name": "People behind the ATM compromise",
      "labels": [
        "hacker"
      ]
    },
    {
      "type": "identity",
      "id": "identity--2d1c6ab3-5e4e-48ac-a32b-f0c01c2836a8",
      "created": "2014-08-08T15:50:10.983464Z",
      "modified": "2014-08-08T15:50:10.983464Z",
      "name": "XYZ Bank",
      "description": "Customer PII and Financial Data were targeted.",
      "identity_class": "organization",
      "sectors": [
        "financial-services"
      ]
    }
  ]
}
